# FreeLinX/ports - xfce/libxfce4util-4.20.1 : meson cross file (FreeLinX musl toolchain).
[binaries]
c = '/home/kanan/FreeLinX-workspace/toolchain/bin/freelinix-cc'
ar = '/home/kanan/FreeLinX-workspace/toolchain/bin/llvm-ar'
ranlib = '/home/kanan/FreeLinX-workspace/toolchain/bin/llvm-ranlib'
strip = '/home/kanan/FreeLinX-workspace/toolchain/bin/llvm-strip'
pkg-config = '/usr/bin/pkg-config'

[properties]
needs_exe_wrapper = false
pkg_config_libdir = '/home/kanan/FreeLinX-workspace/ports/build/deps/libffi/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/glib-2.82.5/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/pcre2-10.48/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/gettext-0.23/lib/pkgconfig'

[built-in options]
c_args = ['-O2', '-Wno-macro-redefined']

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'