# FreeLinX/ports - graphics/utf8proc : meson cross file (FreeLinX musl toolchain).
[binaries]
c       = '/home/kanan/FreeLinX-workspace/toolchain/bin/freelinix-cc'
ar      = '/home/kanan/FreeLinX-workspace/toolchain/bin/llvm-ar'
ranlib  = '/home/kanan/FreeLinX-workspace/toolchain/bin/llvm-ranlib'
strip   = '/home/kanan/FreeLinX-workspace/toolchain/bin/llvm-strip'
pkg-config = '/usr/bin/pkg-config'

[properties]
needs_exe_wrapper = false
pkg_config_libdir = '/home/kanan/FreeLinX-workspace/ports/build/deps/freetype/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/fontconfig/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/expat/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/zlib/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/libpng/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/pixman/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/utf8proc/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/tllist/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/wayland/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/wayland-protocols/share/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/libxkbcommon/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/libffi/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/glib-2.82.5/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/pcre2-10.48/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/fribidi-1.0.16/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/gettext-0.23/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/harfbuzz-14.4.0/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/atk-2.38.0/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/cairo-1.18.4/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/gdk-pixbuf-2.42.12/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/pango-1.56.4/lib/pkgconfig:/home/kanan/FreeLinX-workspace/ports/build/deps/gtk-3.24.52/lib/pkgconfig'

[built-in options]
c_args = ['-O2', '-D_GNU_SOURCE']

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'